title: Plant Humanities Lab
author:
  name: rsnyder
  email: ron@snyderjr.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >-
  Explore the cultural histories of plants and their influence on human societies.

github:
  owner: plant-humanities
  repo: essays
  branch: main

url: https://plant-humanities.github.io/essays/
baseurl: /essays/

components: /essays/juncture/wc/dist/js/index.js